### PR TITLE
add example prusa slicer/superslicer postprocessing script

### PR DESCRIPTION
**Pull request by jtrmal**
Hi, would there be an interest for adding an example script like this?
It's just a draft, I have to test all the flow paths but I think the logic should be clear.
The benefit is that it will figure out the name of the printer dynamically, i.e. you don't have to hardcode it your prusa slicer
Comments/opinions/suggestions welcome.

### CODE REVIEW

**Comment by jtrmal** [comment]
The script uses printer name to get the live config. If the printer is not available, it will either use existing config file or just "succeeds silently".

**Comment by jtrmal** [comment]
OK, I think I'm done with what I have planned. Let me know if you want something differently

**Comment by dalegaard** [comment]
Hi @jtrmal 

Other than a few typos(I'll fix those when merging) it looks good to me!

Could you add a copyright notice at the top, something like:
```
# Copyright (c) 2022 Lasse Dalegaard
# MIT licensed
```
You can pick any open license you wish. I want to ensure that attribution gets carried forward for all contributed scripts.

Best regards,
Lasse

**Comment by jtrmal** [comment]
Done. Thank you for your considerations

**Comment by dalegaard** [comment]
Hi @jtrmal 

I did some cosmetic cleanups and merged this. Not sure why GitHub didn't pick it up correctly, but it's on master now so I'll close this :-)

Thanks!

Best regards,
Lasse

**Pull request closed without merging**
