### PR TITLE
Round M73 P to 3 decimal places

### PR DESCRIPTION
**Pull request by garethky**
Makes the P parameter a float to match klipper's support for floats

### CODE REVIEW

**Comment by garethky** [comment]
I couldn't get the build to workflow to complete in my fork. Looks to be something other than a coding error.

**Comment by dalegaard** [comment]
Hi @garethky 

The build thing is because of the versioning from git tag. Since your repo has no tags, I think that's causing it to fail. I'll look into something for that later on.

As to code, obviously looks fine. I've run `cargo fmt`, so merged :-)

Best regards,
Lasse

**Comment by garethky** [comment]
@dalegaard thanks! Ho can I get an artifact from the build to test it with?

**Comment by dalegaard** [comment]
Hi @garethky 

I've released 2.0.6 with this change and also fixed the `build.rs` script to no longer fail outside git repos. You can either update your own branch and trigger a build, you can use the pre-built artifacts, or you can build locally :-)

Best regards,
Lasse

**Comment by garethky** [comment]
Thank you! I grabbed the binary and see the expected out out:
```
M73 P2.838 R353
...
M73 P3.026 R353
```

I need to get some time over the long weekend to compare the behavior of KlipperScreen and Fluidd before and after the patch, maybe grab some video.

**Pull request merged**
